### ISSUE TITLE
Varied source vector does not include an x1 term.

### ISSUE THREAD

**Issue by jubjamie** [betts-jt/Mod_Sim_-Matlab_FEM_Model#1]
https://github.com/betts-jt/Mod_Sim_-Matlab_FEM_Model/blob/0469e0e3172481aee0bb43cdfbbb93533c89712d/Code/LocalElementVec_VariedSource.m#L16 Needs a x1 term in the second element.

**Comment by jubjamie** [comment]
Did this fix it?

**Comment by betts-jt** [comment]
I believe so yeah
